export interface Suspect {
  id: string;
  name: string;
  statement: string;
  errorIdx: number | null;
  correctWord?: string;
}

export interface CaseDef {
  id: number;
  level: number;
  label: string;
  title: string;
  briefing: string;
  suspects: Suspect[];
  guiltySuspectId: string;
  explanation: string;
  grammarType: string;
  usage: string;
  xp: number;
}

export interface HistoryEntry {
  id: number;
  title: string;
  xp: number;
  grammarType: string;
  usage: string;
}

export const CASES: CaseDef[] = [
  {
    id: 1,
    level: 1,
    label: "CASE 01 · LEVEL 1",
    title: "The Missing Mascot",
    briefing:
      "The school mascot vanished from the gym storage room overnight. Three students were near the gym that night — their statements were collected, but one alibi doesn’t hold up.",
    guiltySuspectId: "taylor",
    suspects: [
      {
        id: "jordan",
        name: "JORDAN LEE",
        statement: "I was at the library until eight, then I walked straight home.",
        errorIdx: null,
      },
      {
        id: "taylor",
        name: "TAYLOR MORAN",
        statement: "I was already their when the alarm rang.",
        errorIdx: 3,
        correctWord: "there",
      },
      {
        id: "morgan",
        name: "MORGAN BLAKE",
        statement: "I had already left the gym before the lights went out.",
        errorIdx: null,
      },
    ],
    explanation: '"There" refers to a place; "their" shows possession.',
    grammarType: "Homophones — there / their / they’re",
    usage:
      'Use "there" for place or existence ("put it there"), "their" for possession ("their car"), and "they’re" as a contraction of "they are".',
    xp: 100,
  },
  {
    id: 2,
    level: 2,
    label: "CASE 02 · LEVEL 2",
    title: "The Locked Gymnasium",
    briefing:
      "The gymnasium door was found locked from the inside. Three students give their account of who checked the lock last — but one statement contradicts itself grammatically.",
    guiltySuspectId: "sam",
    suspects: [
      {
        id: "riley",
        name: "RILEY CHEN",
        statement: "I locked up right after practice ended.",
        errorIdx: null,
      },
      {
        id: "sam",
        name: "SAM OKAFOR",
        statement: "She don't remember locking the door.",
        errorIdx: 1,
        correctWord: "doesn't",
      },
      {
        id: "avery",
        name: "AVERY SINGH",
        statement: "I checked the door twice before I left.",
        errorIdx: null,
      },
    ],
    explanation: '"Doesn’t" agrees with a singular subject like "she".',
    grammarType: "Subject–Verb Agreement",
    usage:
      'Pair "doesn’t" with he/she/it or a singular noun; use "don’t" with I/you/we/they or a plural noun.',
    xp: 150,
  },
  {
    id: 3,
    level: 3,
    label: "CASE 03 · LEVEL 3",
    title: "The Cafeteria Incident",
    briefing:
      "Food went missing from the cafeteria before lunch. Three staff members gave their account of that morning — one timeline doesn’t line up.",
    guiltySuspectId: "casey",
    suspects: [
      {
        id: "drew",
        name: "DREW PATEL",
        statement: "I was refilling trays when the bell rang.",
        errorIdx: null,
      },
      {
        id: "casey",
        name: "CASEY NAKAMURA",
        statement: "By the time I arrive, everyone was already gone.",
        errorIdx: 4,
        correctWord: "arrived",
      },
      {
        id: "jamie",
        name: "JAMIE ROSS",
        statement: "I saw the tray cart still full at noon.",
        errorIdx: null,
      },
    ],
    explanation:
      '"Arrived" (past tense) matches the earlier point in the timeline set up by "by the time".',
    grammarType: "Past Tense & Timeline Sequencing",
    usage:
      'When "by the time" marks an earlier point, use simple past ("arrived") for the event that already happened by then.',
    xp: 200,
  },
  {
    id: 4,
    level: 4,
    label: "CASE 04 · LEVEL 4",
    title: "The Vanishing Trophy",
    briefing: "The trophy case was found empty before first period. Three team captains were the last ones near it.",
    guiltySuspectId: "piper",
    suspects: [
      {
        id: "piper",
        name: "PIPER LANE",
        statement: "The cart lost it's wheel again last week.",
        errorIdx: 3,
        correctWord: "its",
      },
      {
        id: "reed",
        name: "REED ORTIZ",
        statement: "I signed the trophy out for polishing on Tuesday.",
        errorIdx: null,
      },
      {
        id: "noah",
        name: "NOAH FISCHER",
        statement: "I checked the case at seven and it was still full.",
        errorIdx: null,
      },
    ],
    explanation: '"Its" shows possession; "it’s" is a contraction of "it is".',
    grammarType: "Possessives — its / it's",
    usage: 'Use "its" before a noun to show ownership ("its handle"), and "it’s" only when you mean "it is" or "it has".',
    xp: 100,
  },
  {
    id: 5,
    level: 5,
    label: "CASE 05 · LEVEL 5",
    title: "The Hallway Note",
    briefing: "An anonymous note turned up in the office mailbox. Three students who passed the office that morning gave statements.",
    guiltySuspectId: "devon",
    suspects: [
      {
        id: "haley",
        name: "HALEY KIM",
        statement: "I dropped off the mail before homeroom like always.",
        errorIdx: null,
      },
      {
        id: "devon",
        name: "DEVON PRICE",
        statement: "Your going to want to see this note.",
        errorIdx: 0,
        correctWord: "You're",
      },
      {
        id: "marcus",
        name: "MARCUS WELLS",
        statement: "I was in the office the whole time signing in late.",
        errorIdx: null,
      },
    ],
    explanation: '"You’re" is a contraction of "you are"; "your" shows possession.',
    grammarType: "Contractions — your / you're",
    usage: 'Use "your" before a noun ("your locker"), and "you’re" only when you mean "you are".',
    xp: 100,
  },
  {
    id: 6,
    level: 6,
    label: "CASE 06 · LEVEL 6",
    title: "The Broken Projector",
    briefing: "The AV cart short-circuited mid-class. Three students had touched it that period.",
    guiltySuspectId: "tessa",
    suspects: [
      {
        id: "omar",
        name: "OMAR HADDAD",
        statement: "I plugged the cart in but never touched the settings.",
        errorIdx: null,
      },
      {
        id: "lila",
        name: "LILA STRAND",
        statement: "I was across the room filming the whole thing.",
        errorIdx: null,
      },
      {
        id: "tessa",
        name: "TESSA MORROW",
        statement: "The prank didn't effect anyone in the end.",
        errorIdx: 3,
        correctWord: "affect",
      },
    ],
    explanation: '"Affect" is usually a verb (to influence); "effect" is usually a noun (a result).',
    grammarType: "Affect vs. Effect",
    usage: 'Use "affect" when something changes something else ("it affected the outcome"), and "effect" for the result itself ("the effect was obvious").',
    xp: 100,
  },
  {
    id: 7,
    level: 7,
    label: "CASE 07 · LEVEL 7",
    title: "The Cafeteria Line Cut",
    briefing: "Someone jumped the lunch line and knocked over a tray stack. Three students were near the front.",
    guiltySuspectId: "cole",
    suspects: [
      {
        id: "cole",
        name: "COLE BENNETT",
        statement: "I'd rather stay quiet then get blamed for it.",
        errorIdx: 4,
        correctWord: "than",
      },
      {
        id: "zoe",
        name: "ZOE ALVAREZ",
        statement: "I was still in the hallway when the trays fell.",
        errorIdx: null,
      },
      {
        id: "ian",
        name: "IAN MACK",
        statement: "I helped stack the trays back up right after.",
        errorIdx: null,
      },
    ],
    explanation: '"Than" is for comparisons; "then" refers to time or sequence.',
    grammarType: "Then vs. Than",
    usage: 'Use "than" to compare ("faster than"), and "then" for what happens next ("then I left").',
    xp: 100,
  },
  {
    id: 8,
    level: 8,
    label: "CASE 08 · LEVEL 8",
    title: "The Missing Window Latch",
    briefing: "A classroom window was found unlatched after hours. Three students had stayed late that day.",
    guiltySuspectId: "greta",
    suspects: [
      {
        id: "felix",
        name: "FELIX ADEYEMI",
        statement: "I was in detention until the janitor locked up.",
        errorIdx: null,
      },
      {
        id: "greta",
        name: "GRETA SOLIS",
        statement: "Whom left the window open is still unclear to me.",
        errorIdx: 0,
        correctWord: "Who",
      },
      {
        id: "ruby",
        name: "RUBY CHASE",
        statement: "I left through the front doors like everyone else.",
        errorIdx: null,
      },
    ],
    explanation: '"Who" is a subject pronoun; "whom" is an object pronoun.',
    grammarType: "Who vs. Whom",
    usage: 'Use "who" when it performs the action ("who left"), and "whom" only when it receives the action ("to whom").',
    xp: 100,
  },
  {
    id: 9,
    level: 9,
    label: "CASE 09 · LEVEL 9",
    title: "The Locker Room Nap",
    briefing: "A gym teacher found someone had been resting on the equipment mats mid-period. Three students were unaccounted for then.",
    guiltySuspectId: "sasha",
    suspects: [
      {
        id: "tobias",
        name: "TOBIAS RENN",
        statement: "I was running laps the entire period, ask anyone.",
        errorIdx: null,
      },
      {
        id: "nadia",
        name: "NADIA FARROW",
        statement: "I was handing out the equipment near the door.",
        errorIdx: null,
      },
      {
        id: "sasha",
        name: "SASHA DUNN",
        statement: "I told him to lay down before the coach saw.",
        errorIdx: 4,
        correctWord: "lie",
      },
    ],
    explanation: '"Lie" means to recline (no object); "lay" means to place something down (needs an object).',
    grammarType: "Lie vs. Lay",
    usage: 'Use "lie" for a person resting ("lie down"), and "lay" only when something is being placed ("lay it down").',
    xp: 100,
  },
  {
    id: 10,
    level: 10,
    label: "CASE 10 · LEVEL 10",
    title: "The Short Attendance",
    briefing: "Homeroom attendance came up short by three names. The teacher asked the last three who arrived to explain.",
    guiltySuspectId: "wren",
    suspects: [
      {
        id: "wren",
        name: "WREN OKAFOR",
        statement: "There were less students in the hallway than usual.",
        errorIdx: 2,
        correctWord: "fewer",
      },
      {
        id: "darius",
        name: "DARIUS PLUM",
        statement: "I signed in exactly on time, right at the bell.",
        errorIdx: null,
      },
      {
        id: "mia",
        name: "MIA THISTLE",
        statement: "I was pulled aside by the nurse before homeroom started.",
        errorIdx: null,
      },
    ],
    explanation: '"Fewer" is for countable things; "less" is for uncountable amounts.',
    grammarType: "Fewer vs. Less",
    usage: 'Use "fewer" with things you can count ("fewer students"), and "less" with amounts you can’t ("less time").',
    xp: 100,
  },
  {
    id: 11,
    level: 11,
    label: "CASE 11 · LEVEL 11",
    title: "The Talent Show Slip",
    briefing: "A student tripped the sound board during the talent show rehearsal. Three crew members were backstage.",
    guiltySuspectId: "juno",
    suspects: [
      {
        id: "elias",
        name: "ELIAS GRANT",
        statement: "I was running the curtain the whole rehearsal.",
        errorIdx: null,
      },
      {
        id: "juno",
        name: "JUNO PARK",
        statement: "She sings good when she's not nervous.",
        errorIdx: 2,
        correctWord: "well",
      },
      {
        id: "priya",
        name: "PRIYA NATH",
        statement: "I was setting up chairs in the back the entire time.",
        errorIdx: null,
      },
    ],
    explanation: '"Good" is an adjective describing a noun; "well" is an adverb describing an action.',
    grammarType: "Good vs. Well",
    usage: 'Use "good" to describe a thing or person ("a good singer"), and "well" to describe how an action is done ("sings well").',
    xp: 100,
  },
  {
    id: 12,
    level: 12,
    label: "CASE 12 · LEVEL 12",
    title: "The Missing Hall Pass",
    briefing: "A hall pass disappeared from the front desk. Three students had visited the office that hour.",
    guiltySuspectId: "asher",
    suspects: [
      {
        id: "camille",
        name: "CAMILLE ROSS",
        statement: "I dropped off a form and left right away.",
        errorIdx: null,
      },
      {
        id: "theo",
        name: "THEO BRANCH",
        statement: "I was waiting for the nurse the entire time.",
        errorIdx: null,
      },
      {
        id: "asher",
        name: "ASHER VOGEL",
        statement: "I could of sworn I locked the case.",
        errorIdx: 2,
        correctWord: "have",
      },
    ],
    explanation: '"Could have" is the correct phrase; "could of" is a common mishearing of the contraction "could’ve".',
    grammarType: "Informal Verb Phrases — could of",
    usage: 'Write "could have" (or "could’ve"), never "could of" — the same goes for "should have" and "would have".',
    xp: 100,
  },
  {
    id: 13,
    level: 13,
    label: "CASE 13 · LEVEL 13",
    title: "The Back Door Exit",
    briefing: "Someone slipped out the back gym door during assembly. Three students were seated nearest to it.",
    guiltySuspectId: "kai",
    suspects: [
      {
        id: "kai",
        name: "KAI SUTTON",
        statement: "I seen him leave through the back door.",
        errorIdx: 1,
        correctWord: "saw",
      },
      {
        id: "odette",
        name: "ODETTE MARSH",
        statement: "I stayed seated for the entire assembly, front row.",
        errorIdx: null,
      },
      {
        id: "levi",
        name: "LEVI ASTON",
        statement: "I was leading the count-off up on stage.",
        errorIdx: null,
      },
    ],
    explanation: '"Saw" is the simple past tense of "see"; "seen" needs a helping verb like "have".',
    grammarType: "Irregular Past Tense — see / saw",
    usage: 'Use "saw" alone for a completed past action ("I saw him"), and "seen" only with a helper ("I have seen him").',
    xp: 100,
  },
  {
    id: 14,
    level: 14,
    label: "CASE 14 · LEVEL 14",
    title: "The Skipped Assignment",
    briefing: "A group project folder vanished the night before it was due. Three group members had access to it.",
    guiltySuspectId: "marlow",
    suspects: [
      {
        id: "sienna",
        name: "SIENNA KOVAC",
        statement: "I emailed my slides to the group before midnight.",
        errorIdx: null,
      },
      {
        id: "marlow",
        name: "MARLOW GENTRY",
        statement: "I done my part before the bell rang.",
        errorIdx: 1,
        correctWord: "did",
      },
      {
        id: "august",
        name: "AUGUST REYNA",
        statement: "I printed the folder out myself that morning.",
        errorIdx: null,
      },
    ],
    explanation: '"Did" is the simple past tense of "do"; "done" needs a helping verb like "have".',
    grammarType: "Irregular Past Tense — do / did",
    usage: 'Use "did" alone for a completed past action ("I did it"), and "done" only with a helper ("I have done it").',
    xp: 100,
  },
  {
    id: 15,
    level: 15,
    label: "CASE 15 · LEVEL 15",
    title: "The Early Arrival",
    briefing: "Someone was in the science lab before the building even opened. Three students have keycard access.",
    guiltySuspectId: "ivy",
    suspects: [
      {
        id: "gideon",
        name: "GIDEON PALL",
        statement: "I badge in every morning right at seven-thirty.",
        errorIdx: null,
      },
      {
        id: "fawn",
        name: "FAWN ARCHER",
        statement: "I was dropped off late by my mom that day.",
        errorIdx: null,
      },
      {
        id: "ivy",
        name: "IVY WESTBROOK",
        statement: "She come by the office right after lunch.",
        errorIdx: 1,
        correctWord: "came",
      },
    ],
    explanation: '"Came" is the simple past tense of "come"; "come" needs a helping verb like "have".',
    grammarType: "Irregular Past Tense — come / came",
    usage: 'Use "came" alone for a completed past action ("she came in"), and "come" only with a helper ("she has come in").',
    xp: 100,
  },
  {
    id: 16,
    level: 16,
    label: "CASE 16 · LEVEL 16",
    title: "The Cracked Beaker",
    briefing: "A beaker in the chemistry lab was shattered before class started. Three students had lab access that period.",
    guiltySuspectId: "caspian",
    suspects: [
      {
        id: "caspian",
        name: "CASPIAN DREW",
        statement: "The beaker was already broke when I got there.",
        errorIdx: 4,
        correctWord: "broken",
      },
      {
        id: "mabel",
        name: "MABEL QUINCE",
        statement: "I was still at my locker when the bell rang.",
        errorIdx: null,
      },
      {
        id: "orion",
        name: "ORION FALK",
        statement: "I signed into the lab log five minutes after that.",
        errorIdx: null,
      },
    ],
    explanation: 'The passive voice needs the past participle "broken", not the simple past "broke".',
    grammarType: "Irregular Past Participle — break / broken",
    usage: 'After "was/were" or "has/have", use the past participle ("was broken"), not the simple past ("broke").',
    xp: 100,
  },
  {
    id: 17,
    level: 17,
    label: "CASE 17 · LEVEL 17",
    title: "The Early Fire Drill",
    briefing: "A fire alarm went off ten minutes before the scheduled drill. Three staff aides were near the panel.",
    guiltySuspectId: "luca",
    suspects: [
      {
        id: "briar",
        name: "BRIAR HOLLOWAY",
        statement: "I was walking the lower hall when it started.",
        errorIdx: null,
      },
      {
        id: "luca",
        name: "LUCA STONE",
        statement: "The fire drill begun before I even sat down.",
        errorIdx: 3,
        correctWord: "began",
      },
      {
        id: "esme",
        name: "ESME TALBOT",
        statement: "I was already outside setting up the roster clipboard.",
        errorIdx: null,
      },
    ],
    explanation: '"Began" is the simple past tense of "begin"; "begun" needs a helping verb like "had".',
    grammarType: "Irregular Past Tense — begin / began",
    usage: 'Use "began" alone for a completed past action ("it began"), and "begun" only with a helper ("it had begun").',
    xp: 100,
  },
  {
    id: 18,
    level: 18,
    label: "CASE 18 · LEVEL 18",
    title: "The Missing Lunch Tray",
    briefing: "A lunch tray vanished from the return cart before the last bell. Three students were near the cart.",
    guiltySuspectId: "finnegan",
    suspects: [
      {
        id: "clementine",
        name: "CLEMENTINE VOSS",
        statement: "I was still in line when the bell rang.",
        errorIdx: null,
      },
      {
        id: "remy",
        name: "REMY OSEI",
        statement: "I bussed my tray right to the window like always.",
        errorIdx: null,
      },
      {
        id: "finnegan",
        name: "FINNEGAN COLE",
        statement: "I already eat lunch before the bell rang.",
        errorIdx: 2,
        correctWord: "ate",
      },
    ],
    explanation: '"Ate" is the simple past tense of "eat"; "eaten" needs a helping verb like "had".',
    grammarType: "Irregular Past Tense — eat / ate",
    usage: 'Use "ate" alone for a completed past action ("I ate"), and "eaten" only with a helper ("I had eaten").',
    xp: 100,
  },
  {
    id: 19,
    level: 19,
    label: "CASE 19 · LEVEL 19",
    title: "The Forged Signature",
    briefing: "A permission slip turned up with a signature no one recognized. Three students had slips due that day.",
    guiltySuspectId: "sage",
    suspects: [
      {
        id: "sage",
        name: "SAGE BARLOW",
        statement: "I writed the note before I left the room.",
        errorIdx: 1,
        correctWord: "wrote",
      },
      {
        id: "phoebe",
        name: "PHOEBE LANGSTON",
        statement: "I had my dad sign mine over the weekend.",
        errorIdx: null,
      },
      {
        id: "rowan",
        name: "ROWAN FITCH",
        statement: "I turned my slip in a full day early.",
        errorIdx: null,
      },
    ],
    explanation: '"Wrote" is the simple past tense of "write"; "writed" is not a word.',
    grammarType: "Irregular Past Tense — write / wrote",
    usage: 'The past tense of "write" is "wrote", never "writed" — "written" is the past participle, used with a helper.',
    xp: 100,
  },
  {
    id: 20,
    level: 20,
    label: "CASE 20 · LEVEL 20",
    title: "The Returned Folder",
    briefing: "A missing evidence folder reappeared on the teacher's desk overnight. Three students had classroom keys checked out.",
    guiltySuspectId: "willa",
    suspects: [
      {
        id: "desmond",
        name: "DESMOND HALE",
        statement: "I locked the room and went straight to practice.",
        errorIdx: null,
      },
      {
        id: "willa",
        name: "WILLA CRESS",
        statement: "She bringed the folder back before noon.",
        errorIdx: 1,
        correctWord: "brought",
      },
      {
        id: "annika",
        name: "ANNIKA FROST",
        statement: "I was out sick and never had a key that day.",
        errorIdx: null,
      },
    ],
    explanation: '"Brought" is the simple past tense of "bring"; "bringed" is not a word.',
    grammarType: "Irregular Past Tense — bring / brought",
    usage: 'The past tense of "bring" is always "brought", never "bringed".',
    xp: 100,
  },
  {
    id: 21,
    level: 21,
    label: "CASE 21 · LEVEL 21",
    title: "The Silent Hallway",
    briefing: "A witness claims no one else was around, but the timeline says otherwise. Three students were logged nearby.",
    guiltySuspectId: "bryce",
    suspects: [
      {
        id: "olive",
        name: "OLIVE MARCHETTI",
        statement: "I walked straight past the lockers without stopping.",
        errorIdx: null,
      },
      {
        id: "kieran",
        name: "KIERAN DOSS",
        statement: "I was in the stairwell the entire five minutes.",
        errorIdx: null,
      },
      {
        id: "bryce",
        name: "BRYCE HANLON",
        statement: "I didn't see nobody near the lockers.",
        errorIdx: 3,
        correctWord: "anybody",
      },
    ],
    explanation: 'Two negatives ("didn’t" and "nobody") cancel out and reverse the intended meaning.',
    grammarType: "Double Negatives",
    usage: 'Use only one negative per clause — pair "didn’t" with "anybody", not "nobody".',
    xp: 100,
  },
  {
    id: 22,
    level: 22,
    label: "CASE 22 · LEVEL 22",
    title: "The Exaggerated Excuse",
    briefing: "A student's excuse for a late assignment kept getting more elaborate. Two classmates were asked to weigh in.",
    guiltySuspectId: "penn",
    suspects: [
      {
        id: "penn",
        name: "PENN LOCKWOOD",
        statement: "He's the bestest liar in our class, honestly.",
        errorIdx: 2,
        correctWord: "best",
      },
      {
        id: "harlow",
        name: "HARLOW BIXBY",
        statement: "I heard the same excuse twice, word for word.",
        errorIdx: null,
      },
      {
        id: "tatum",
        name: "TATUM SORREL",
        statement: "I was standing right there when he made it up.",
        errorIdx: null,
      },
    ],
    explanation: '"Bestest" is a non-standard doubling of the superlative; the correct superlative of "good" is "best".',
    grammarType: "Superlatives — informal forms",
    usage: 'The superlative of "good" is simply "best" — never add "-est" a second time.',
    xp: 100,
  },
  {
    id: 23,
    level: 23,
    label: "CASE 23 · LEVEL 23",
    title: "The Gym Equipment Mix-up",
    briefing: "Someone signed out gym equipment under two names. The coach questioned the pair last seen with it.",
    guiltySuspectId: "maxine",
    suspects: [
      {
        id: "bennett",
        name: "BENNETT SHAW",
        statement: "I locked the equipment closet before I left.",
        errorIdx: null,
      },
      {
        id: "maxine",
        name: "MAXINE PEARCE",
        statement: "Me and Jordan were the last ones in the gym.",
        errorIdx: 0,
        correctWord: "I",
      },
      {
        id: "iona",
        name: "IONA WREN",
        statement: "I checked in the basketballs a period earlier.",
        errorIdx: null,
      },
    ],
    explanation: '"I" is a subject pronoun; "me" is an object pronoun and can’t be the subject of a sentence.',
    grammarType: "Pronoun Case — subject pronouns",
    usage: 'Use "I" when the pronoun performs the action ("Jordan and I were there"), never "me".',
    xp: 100,
  },
  {
    id: 24,
    level: 24,
    label: "CASE 24 · LEVEL 24",
    title: "The Supply Closet Search",
    briefing: "The supply closet was left unlocked overnight. Two students admit checking it that afternoon.",
    guiltySuspectId: "corwin",
    suspects: [
      {
        id: "delphine",
        name: "DELPHINE NASH",
        statement: "I was in the office the whole afternoon.",
        errorIdx: null,
      },
      {
        id: "azrael",
        name: "AZRAEL DUNMORE",
        statement: "I picked up the mail and went straight to class.",
        errorIdx: null,
      },
      {
        id: "corwin",
        name: "CORWIN ASHBY",
        statement: "Him and I checked the supply closet together.",
        errorIdx: 0,
        correctWord: "He",
      },
    ],
    explanation: '"He" is a subject pronoun; "him" is an object pronoun and can’t be the subject of a sentence.',
    grammarType: "Pronoun Case — subject pronouns",
    usage: 'Use "he" when the pronoun performs the action ("He and I checked it"), never "him".',
    xp: 100,
  },
  {
    id: 25,
    level: 25,
    label: "CASE 25 · LEVEL 25",
    title: "The Detention Mix-up",
    briefing: "A teacher asked two students to stay after class, but only one showed. The other explained what happened.",
    guiltySuspectId: "rosalind",
    suspects: [
      {
        id: "rosalind",
        name: "ROSALIND KEATS",
        statement: "The teacher asked Riley and I to stay after class.",
        errorIdx: 5,
        correctWord: "me",
      },
      {
        id: "toby",
        name: "TOBY LINDGREN",
        statement: "I stayed exactly as long as she asked me to.",
        errorIdx: null,
      },
      {
        id: "winslow",
        name: "WINSLOW PECK",
        statement: "I wasn't even in that class that period.",
        errorIdx: null,
      },
    ],
    explanation: '"Me" is an object pronoun, correct after a verb like "asked"; "I" is only for the subject position.',
    grammarType: "Pronoun Case — object pronouns",
    usage: 'Use "me" when the pronoun receives the action ("asked Riley and me"), and save "I" for the subject.',
    xp: 100,
  },
  {
    id: 26,
    level: 26,
    label: "CASE 26 · LEVEL 26",
    title: "The Unattended Bags",
    briefing: "A row of bags was left outside the gym during practice. Three students claim they weren't theirs.",
    guiltySuspectId: "gwendolyn",
    suspects: [
      {
        id: "ambrose",
        name: "AMBROSE TATE",
        statement: "I carried my bag straight to the locker room.",
        errorIdx: null,
      },
      {
        id: "gwendolyn",
        name: "GWENDOLYN FAIRE",
        statement: "The students bags were left outside the gym.",
        errorIdx: 1,
        correctWord: "students'",
      },
      {
        id: "severin",
        name: "SEVERIN LOWE",
        statement: "I dropped mine off in the equipment room instead.",
        errorIdx: null,
      },
    ],
    explanation: 'A plural noun ending in "s" takes just an apostrophe to show possession, not "s" alone.',
    grammarType: "Apostrophes — plural possessives",
    usage: 'For a plural noun already ending in "s", add only an apostrophe ("students’ bags"), not a bare "s".',
    xp: 100,
  },
  {
    id: 27,
    level: 27,
    label: "CASE 27 · LEVEL 27",
    title: "The Vent Cover",
    briefing: "A loose vent cover fell during third period. Three students had reported it earlier that week.",
    guiltySuspectId: "percival",
    suspects: [
      {
        id: "cordelia",
        name: "CORDELIA WYNN",
        statement: "I reported the loose cover to the janitor Monday.",
        errorIdx: null,
      },
      {
        id: "lachlan",
        name: "LACHLAN FEY",
        statement: "I was assigned a different hallway that whole week.",
        errorIdx: null,
      },
      {
        id: "percival",
        name: "PERCIVAL DANE",
        statement: "Who's badge is this? It fell near the vents.",
        errorIdx: 0,
        correctWord: "Whose",
      },
    ],
    explanation: '"Whose" shows possession; "who’s" is a contraction of "who is".',
    grammarType: "Whose vs. Who's",
    usage: 'Use "whose" before a noun to show ownership ("whose badge"), and "who’s" only when you mean "who is".',
    xp: 100,
  },
  {
    id: 28,
    level: 28,
    label: "CASE 28 · LEVEL 28",
    title: "The Second Try",
    briefing: "A student claims they tried to help twice but got locked out both times. Two classmates confirm parts of the story.",
    guiltySuspectId: "marigold",
    suspects: [
      {
        id: "marigold",
        name: "MARIGOLD PIKE",
        statement: "I wanted to come to, but I had practice.",
        errorIdx: 4,
        correctWord: "too",
      },
      {
        id: "silas",
        name: "SILAS BRAND",
        statement: "I waited by the door for almost ten minutes.",
        errorIdx: null,
      },
      {
        id: "adelaide",
        name: "ADELAIDE MOSS",
        statement: "I texted ahead to say I'd be late instead.",
        errorIdx: null,
      },
    ],
    explanation: '"Too" means "also" or "excessively"; "to" is a preposition showing direction.',
    grammarType: "To vs. Too",
    usage: 'Use "too" when you mean "also" ("me too") or "excessively" ("too loud"), and "to" for direction or infinitives.',
    xp: 100,
  },
  {
    id: 29,
    level: 29,
    label: "CASE 29 · LEVEL 29",
    title: "The Group Chat Leak",
    briefing: "Screenshots from a private group chat were leaked. Everyone but one student claims they weren't in the chat.",
    guiltySuspectId: "thaddeus",
    suspects: [
      {
        id: "isolde",
        name: "ISOLDE VANCE",
        statement: "I left the chat weeks before any of this happened.",
        errorIdx: null,
      },
      {
        id: "thaddeus",
        name: "THADDEUS ORME",
        statement: "Everyone accept Jordan was in the library that hour.",
        errorIdx: 1,
        correctWord: "except",
      },
      {
        id: "barnaby",
        name: "BARNABY CRESSWELL",
        statement: "I never had my phone on me that period.",
        errorIdx: null,
      },
    ],
    explanation: '"Accept" means to receive or agree to something; "except" means excluding something.',
    grammarType: "Accept vs. Except",
    usage: 'Use "accept" when you mean "to receive" ("accept the blame"), and "except" when you mean "excluding" ("everyone except him").',
    xp: 100,
  },
  {
    id: 30,
    level: 30,
    label: "CASE 30 · LEVEL 30",
    title: "The Missing Hall Pass, Again",
    briefing: "A second hall pass went missing from the same desk drawer. Two students often borrow passes from there.",
    guiltySuspectId: "florence",
    suspects: [
      {
        id: "alistair",
        name: "ALISTAIR QUIGLEY",
        statement: "I always clip my pass to my bag strap.",
        errorIdx: null,
      },
      {
        id: "petra",
        name: "PETRA LINDQVIST",
        statement: "I turned mine back in the same day I got it.",
        errorIdx: null,
      },
      {
        id: "florence",
        name: "FLORENCE ODUYA",
        statement: "I didn't want to loose my hall pass again.",
        errorIdx: 4,
        correctWord: "lose",
      },
    ],
    explanation: '"Lose" means to misplace something (verb); "loose" means not tight (adjective).',
    grammarType: "Loose vs. Lose",
    usage: 'Use "lose" for misplacing or failing to keep something ("lose my pass"), and "loose" to describe something not secure.',
    xp: 100,
  },
  {
    id: 31,
    level: 31,
    label: "CASE 31 · LEVEL 31",
    title: "The Principal's Office",
    briefing: "A note requesting a meeting was left with the wrong name on it. Three students were called down that day.",
    guiltySuspectId: "ezra",
    suspects: [
      {
        id: "ezra",
        name: "EZRA THISTLEWOOD",
        statement: "I went to see the school principle about the fight.",
        errorIdx: 6,
        correctWord: "principal",
      },
      {
        id: "seraphina",
        name: "SERAPHINA LUND",
        statement: "I was called down for a totally separate reason.",
        errorIdx: null,
      },
      {
        id: "galen",
        name: "GALEN ASHFORD",
        statement: "I never left class the whole afternoon.",
        errorIdx: null,
      },
    ],
    explanation: '"Principal" refers to the school’s head administrator (or means "main"); "principle" means a rule or belief.',
    grammarType: "Principal vs. Principle",
    usage: 'Use "principal" for the school leader or the main thing, and "principle" for a rule or fundamental truth.',
    xp: 100,
  },
  {
    id: 32,
    level: 32,
    label: "CASE 32 · LEVEL 32",
    title: "The Idle Cart",
    briefing: "A supply cart sat in the same spot for two days straight. Two students were assigned to move it.",
    guiltySuspectId: "octavia",
    suspects: [
      {
        id: "leopold",
        name: "LEOPOLD SAGE",
        statement: "I moved a different cart entirely, not that one.",
        errorIdx: null,
      },
      {
        id: "octavia",
        name: "OCTAVIA REN",
        statement: "The cart was stationery by the door the whole time.",
        errorIdx: 3,
        correctWord: "stationary",
      },
      {
        id: "marisol",
        name: "MARISOL EKWUEME",
        statement: "I was told to leave it exactly where it was.",
        errorIdx: null,
      },
    ],
    explanation: '"Stationary" means not moving; "stationery" refers to paper and writing supplies.',
    grammarType: "Stationary vs. Stationery",
    usage: 'Use "stationary" to describe something that isn’t moving, and "stationery" for paper, envelopes, and pens.',
    xp: 100,
  },
  {
    id: 33,
    level: 33,
    label: "CASE 33 · LEVEL 33",
    title: "The Awkward Thank-You",
    briefing: "A thank-you note to the coach caused some confusion about its wording. Two teammates were asked about it.",
    guiltySuspectId: "fenwick",
    suspects: [
      {
        id: "rosamund",
        name: "ROSAMUND ITZEL",
        statement: "I wrote a separate card that never got signed.",
        errorIdx: null,
      },
      {
        id: "constantine",
        name: "CONSTANTINE VELEZ",
        statement: "I wasn't even at that game, I was sick.",
        errorIdx: null,
      },
      {
        id: "fenwick",
        name: "FENWICK OYELARAN",
        statement: "She gave the coach a nice complement after the game.",
        errorIdx: 6,
        correctWord: "compliment",
      },
    ],
    explanation: '"Compliment" means a nice remark; "complement" means something that completes or matches.',
    grammarType: "Complement vs. Compliment",
    usage: 'Use "compliment" for a nice remark ("gave a compliment"), and "complement" for something that completes another thing.',
    xp: 100,
  },
  {
    id: 34,
    level: 34,
    label: "CASE 34 · LEVEL 34",
    title: "The Confused Timeline",
    briefing: "A student wasn't sure if an event happened before or after the bell. Two classmates helped narrow it down.",
    guiltySuspectId: "perpetua",
    suspects: [
      {
        id: "perpetua",
        name: "PERPETUA NAKASHIMA",
        statement: "I wasn't sure weather I should say anything.",
        errorIdx: 3,
        correctWord: "whether",
      },
      {
        id: "leopoldine",
        name: "LEOPOLDINE ASANTE",
        statement: "I was outside checking the actual weather, ironically.",
        errorIdx: null,
      },
      {
        id: "tristram",
        name: "TRISTRAM OYELOWO",
        statement: "I didn't hear about any of it until lunch.",
        errorIdx: null,
      },
    ],
    explanation: '"Whether" introduces a choice between options; "weather" refers to atmospheric conditions.',
    grammarType: "Weather vs. Whether",
    usage: 'Use "whether" when presenting a choice ("whether I should"), and "weather" only for rain, wind, and temperature.',
    xp: 100,
  },
  {
    id: 35,
    level: 35,
    label: "CASE 35 · LEVEL 35",
    title: "The Sudden Silence",
    briefing: "The hallway went unusually quiet right before the incident. Two hall monitors were asked to describe it.",
    guiltySuspectId: "barnabas",
    suspects: [
      {
        id: "eulalia",
        name: "EULALIA MBEKI",
        statement: "I was still talking loudly the whole time, honestly.",
        errorIdx: null,
      },
      {
        id: "barnabas",
        name: "BARNABAS OKONKWO",
        statement: "It got pretty quite in the hallway after that.",
        errorIdx: 3,
        correctWord: "quiet",
      },
      {
        id: "severus",
        name: "SEVERUS ADEBAYO",
        statement: "I noticed nothing different about the hallway at all.",
        errorIdx: null,
      },
    ],
    explanation: '"Quiet" means making little noise; "quite" means "rather" or "completely".',
    grammarType: "Quiet vs. Quite",
    usage: 'Use "quiet" to describe low noise ("the hallway got quiet"), and "quite" only as an intensifier ("quite tired").',
    xp: 100,
  },
  {
    id: 36,
    level: 36,
    label: "CASE 36 · LEVEL 36",
    title: "The Line Leader",
    briefing: "Someone led the class line out during the drill without being assigned. Two line leaders were questioned.",
    guiltySuspectId: "griselda",
    suspects: [
      {
        id: "theodric",
        name: "THEODRIC ASOGWA",
        statement: "I was at the back of the line the whole time.",
        errorIdx: null,
      },
      {
        id: "paloma",
        name: "PALOMA IGWE",
        statement: "I was assigned crowd control by the exit instead.",
        errorIdx: null,
      },
      {
        id: "griselda",
        name: "GRISELDA OKAFOR",
        statement: "She lead the group out during the drill yesterday.",
        errorIdx: 1,
        correctWord: "led",
      },
    ],
    explanation: '"Led" is the simple past tense of "lead"; "lead" (rhymes with "seed") is the present tense.',
    grammarType: "Irregular Past Tense — lead / led",
    usage: 'The past tense of "lead" is spelled "led", not "lead" — that spelling is reserved for the present tense.',
    xp: 100,
  },
  {
    id: 37,
    level: 37,
    label: "CASE 37 · LEVEL 37",
    title: "The Replacement Lock",
    briefing: "A new lock appeared on a locker overnight, unrequested. Two students admit visiting the hardware closet.",
    guiltySuspectId: "augustine",
    suspects: [
      {
        id: "augustine",
        name: "AUGUSTINE OKORO",
        statement: "I boughten a new lock after mine went missing.",
        errorIdx: 1,
        correctWord: "bought",
      },
      {
        id: "cassia",
        name: "CASSIA NNAMDI",
        statement: "I still have my original lock, never replaced it.",
        errorIdx: null,
      },
      {
        id: "percival",
        name: "PERCIVAL ADEOLA",
        statement: "I don't even use a lock on my locker.",
        errorIdx: null,
      },
    ],
    explanation: 'The past tense of "buy" is "bought"; "boughten" is a non-standard form.',
    grammarType: "Irregular Past Tense — buy / bought",
    usage: 'The past tense of "buy" is always "bought" — "boughten" is not a standard English word.',
    xp: 100,
  },
  {
    id: 38,
    level: 38,
    label: "CASE 38 · LEVEL 38",
    title: "The Borrowed Pencil",
    briefing: "A pencil case went around the room and one item never came back. Two students admit passing it along.",
    guiltySuspectId: "wilhelmina",
    suspects: [
      {
        id: "leopoldo",
        name: "LEOPOLDO ADEYINKA",
        statement: "I passed the case along without opening it.",
        errorIdx: null,
      },
      {
        id: "wilhelmina",
        name: "WILHELMINA OSEI",
        statement: "She asked to borrow me a pencil before class.",
        errorIdx: 3,
        correctWord: "lend",
      },
      {
        id: "seraphim",
        name: "SERAPHIM CHUKWU",
        statement: "I never touched the pencil case at all that day.",
        errorIdx: null,
      },
    ],
    explanation: '"Lend" means to give something temporarily; "borrow" means to receive something temporarily.',
    grammarType: "Borrow vs. Lend",
    usage: 'Use "lend" when you’re giving something out, and "borrow" when you’re the one receiving it.',
    xp: 100,
  },
  {
    id: 39,
    level: 39,
    label: "CASE 39 · LEVEL 39",
    title: "The Split Blame",
    briefing: "Three students were caught with the same broken equipment. The coach wanted to know how blame should be split.",
    guiltySuspectId: "othello",
    suspects: [
      {
        id: "eulogia",
        name: "EULOGIA NWACHUKWU",
        statement: "I only touched the equipment for a second.",
        errorIdx: null,
      },
      {
        id: "bartholomew",
        name: "BARTHOLOMEW EZEIGWE",
        statement: "I wasn't in the room when it broke at all.",
        errorIdx: null,
      },
      {
        id: "othello",
        name: "OTHELLO BANKOLE",
        statement: "Split the blame between the three of us evenly.",
        errorIdx: 3,
        correctWord: "among",
      },
    ],
    explanation: '"Between" is traditionally used for exactly two; "among" is used for three or more.',
    grammarType: "Between vs. Among",
    usage: 'Use "between" for two people or things, and "among" when there are three or more.',
    xp: 100,
  },
  {
    id: 40,
    level: 40,
    label: "CASE 40 · LEVEL 40",
    title: "The Locked Doors",
    briefing: "Two side doors were both found unlocked before anyone arrived. A witness described checking on them.",
    guiltySuspectId: "valentina",
    suspects: [
      {
        id: "valentina",
        name: "VALENTINA OYELARAN",
        statement: "Neither of the doors were locked that morning.",
        errorIdx: 4,
        correctWord: "was",
      },
      {
        id: "firmin",
        name: "FIRMIN ADESANYA",
        statement: "I checked both doors myself right after first bell.",
        errorIdx: null,
      },
      {
        id: "odalys",
        name: "ODALYS NNAJI",
        statement: "I wasn't assigned to check any doors that day.",
        errorIdx: null,
      },
    ],
    explanation: '"Neither" is a singular subject and takes a singular verb, even though it refers to two things.',
    grammarType: "Subject–Verb Agreement — neither/either",
    usage: 'Treat "neither" and "either" as singular subjects — pair them with "was", not "were".',
    xp: 100,
  },
  {
    id: 41,
    level: 41,
    label: "CASE 41 · LEVEL 41",
    title: "The Surprised Reaction",
    briefing: "A student reacted strongly to news about a canceled event. Two classmates described how surprised they seemed.",
    guiltySuspectId: "cordell",
    suspects: [
      {
        id: "anemone",
        name: "ANEMONE IGWEBUIKE",
        statement: "I wasn't surprised at all, honestly, I expected it.",
        errorIdx: null,
      },
      {
        id: "cordell",
        name: "CORDELL ASOGWA",
        statement: "I was real surprised when the alarm went off.",
        errorIdx: 2,
        correctWord: "really",
      },
      {
        id: "thornton",
        name: "THORNTON OKEKE",
        statement: "I missed the announcement completely that period.",
        errorIdx: null,
      },
    ],
    explanation: '"Really" is an adverb that modifies an adjective like "surprised"; "real" is an adjective and can’t do that job.',
    grammarType: "Real vs. Really",
    usage: 'Use "really" to intensify an adjective or verb ("really surprised"), and save "real" for describing a noun ("a real problem").',
    xp: 100,
  },
  {
    id: 42,
    level: 42,
    label: "CASE 42 · LEVEL 42",
    title: "The Rough Morning",
    briefing: "A student showed up visibly upset and left early. Two friends were asked how they seemed that morning.",
    guiltySuspectId: "perpetua",
    suspects: [
      {
        id: "lionel",
        name: "LIONEL NWOSU",
        statement: "I saw her at lunch and she seemed fine.",
        errorIdx: null,
      },
      {
        id: "augusta",
        name: "AUGUSTA OYELEKE",
        statement: "I wasn't around her at all that morning.",
        errorIdx: null,
      },
      {
        id: "perpetua",
        name: "PERPETUA ADEBIYI",
        statement: "I felt badly about missing the bell that day.",
        errorIdx: 2,
        correctWord: "bad",
      },
    ],
    explanation: '"Feel" is a linking verb here, so it takes an adjective ("bad"), not an adverb ("badly").',
    grammarType: "Adjective vs. Adverb — bad / badly",
    usage: 'After linking verbs like "feel", "look", or "seem", use an adjective ("felt bad"), not an adverb ("felt badly").',
    xp: 100,
  },
  {
    id: 43,
    level: 43,
    label: "CASE 43 · LEVEL 43",
    title: "The Hallway Pass Grab",
    briefing: "A pass was grabbed off the desk without asking. Two students were nearby when it happened.",
    guiltySuspectId: "isadora",
    suspects: [
      {
        id: "isadora",
        name: "ISADORA MENSAH",
        statement: "I grabbed an hallway pass before running to class.",
        errorIdx: 2,
        correctWord: "a",
      },
      {
        id: "rufus",
        name: "RUFUS ADJEI",
        statement: "I was already in the hallway when it happened.",
        errorIdx: null,
      },
      {
        id: "philomena",
        name: "PHILOMENA DARKO",
        statement: "I signed my own pass out earlier that morning.",
        errorIdx: null,
      },
    ],
    explanation: 'Use "an" before a word that starts with a vowel sound, and "a" before a word that starts with a consonant sound.',
    grammarType: "Articles — a vs. an",
    usage: 'Choose "an" before vowel sounds ("an hour") and "a" before consonant sounds ("a hallway pass").',
    xp: 100,
  },
  {
    id: 44,
    level: 44,
    label: "CASE 44 · LEVEL 44",
    title: "The Curious Vent",
    briefing: "A student got caught investigating a vent that had been rattling for days. Two classmates weighed in on why.",
    guiltySuspectId: "beatrix",
    suspects: [
      {
        id: "maximilian",
        name: "MAXIMILIAN NWANKWO",
        statement: "I've never once thought about the vents, honestly.",
        errorIdx: null,
      },
      {
        id: "beatrix",
        name: "BEATRIX OYELARAN",
        statement: "I've always been interested on how the vents connect.",
        errorIdx: 4,
        correctWord: "in",
      },
      {
        id: "sylvia",
        name: "SYLVIA CHUKWUEMEKA",
        statement: "I reported the rattling noise a week ago already.",
        errorIdx: null,
      },
    ],
    explanation: 'The standard preposition after "interested" is "in", not "on".',
    grammarType: "Prepositions — interested in",
    usage: 'Say "interested in" something, not "interested on" — that pairing is nonstandard in English.',
    xp: 100,
  },
  {
    id: 45,
    level: 45,
    label: "CASE 45 · LEVEL 45",
    title: "The Riddle Contest",
    briefing: "A riddle contest ended in a dispute about who solved a clue first. Two contestants gave their side.",
    guiltySuspectId: "wendell",
    suspects: [
      {
        id: "anastasia",
        name: "ANASTASIA EZENWA",
        statement: "I solved it second, right after the first buzzer.",
        errorIdx: null,
      },
      {
        id: "cornelius",
        name: "CORNELIUS OBIAGELI",
        statement: "I wasn't even entered in that round.",
        errorIdx: null,
      },
      {
        id: "wendell",
        name: "WENDELL ACHEBE",
        statement: "I've never been good in solving riddles like this.",
        errorIdx: 4,
        correctWord: "at",
      },
    ],
    explanation: 'The standard preposition after "good" (meaning skilled) is "at", not "in".',
    grammarType: "Prepositions — good at",
    usage: 'Say "good at" a skill or activity ("good at riddles"), not "good in".',
    xp: 100,
  },
  {
    id: 46,
    level: 46,
    label: "CASE 46 · LEVEL 46",
    title: "The Hypothetical Plan",
    briefing: "A student described what they would have done differently, hypothetically. Two classmates weighed in on the plan.",
    guiltySuspectId: "ophelia",
    suspects: [
      {
        id: "ophelia",
        name: "OPHELIA NWACHUKWU",
        statement: "If I was in charge, I'd have locked the gym myself.",
        errorIdx: 2,
        correctWord: "were",
      },
      {
        id: "reginald",
        name: "REGINALD ADEBOWALE",
        statement: "I would've just called the office right away.",
        errorIdx: null,
      },
      {
        id: "marguerite",
        name: "MARGUERITE OKONJO",
        statement: "I wasn't in charge of anything that day.",
        errorIdx: null,
      },
    ],
    explanation: 'The subjunctive mood uses "were" (not "was") for hypothetical situations after "if".',
    grammarType: "Subjunctive Mood — if I were",
    usage: 'In hypothetical "if" statements, use "were" for all subjects, even "I" — "if I were in charge".',
    xp: 100,
  },
  {
    id: 47,
    level: 47,
    label: "CASE 47 · LEVEL 47",
    title: "The Thin Crowd",
    briefing: "The assembly had a noticeably thin turnout. Two hall monitors were asked to estimate the crowd.",
    guiltySuspectId: "theodora",
    suspects: [
      {
        id: "augustine",
        name: "AUGUSTINE OKAFOR",
        statement: "I counted almost the whole class still there.",
        errorIdx: null,
      },
      {
        id: "theodora",
        name: "THEODORA NNAEMEKA",
        statement: "There wasn't much students left when the bell rang.",
        errorIdx: 2,
        correctWord: "many",
      },
      {
        id: "rosalind",
        name: "ROSALIND ADEYEMO",
        statement: "I left before the bell, so I can't say.",
        errorIdx: null,
      },
    ],
    explanation: '"Many" is for countable nouns like "students"; "much" is for uncountable nouns.',
    grammarType: "Countable Nouns — much / many",
    usage: 'Use "many" with things you can count ("many students"), and "much" with things you can’t ("much time").',
    xp: 100,
  },
  {
    id: 48,
    level: 48,
    label: "CASE 48 · LEVEL 48",
    title: "The Assembly Headcount",
    briefing: "The assembly headcount didn't match the sign-in sheet. Two student aides handled the sign-in.",
    guiltySuspectId: "cassandra",
    suspects: [
      {
        id: "leopold",
        name: "LEOPOLD ADEKUNLE",
        statement: "I checked names off the sheet the entire time.",
        errorIdx: null,
      },
      {
        id: "hortensia",
        name: "HORTENSIA NNAMDI",
        statement: "I wasn't assigned to sign-in duty that day.",
        errorIdx: null,
      },
      {
        id: "cassandra",
        name: "CASSANDRA OBI",
        statement: "A large amount of students showed up for the assembly.",
        errorIdx: 2,
        correctWord: "number",
      },
    ],
    explanation: '"Number" is for countable things; "amount" is for uncountable quantities.',
    grammarType: "Amount vs. Number",
    usage: 'Use "number" with things you can count ("a number of students"), and "amount" with things you can’t ("an amount of time").',
    xp: 100,
  },
  {
    id: 49,
    level: 49,
    label: "CASE 49 · LEVEL 49",
    title: "The Empty Locker Room",
    briefing: "A locker room was reported emptied out faster than expected. Two students described who was left.",
    guiltySuspectId: "fredericka",
    suspects: [
      {
        id: "fredericka",
        name: "FREDERICKA ANIEFIOK",
        statement: "Three persons were still in the locker room when I left.",
        errorIdx: 1,
        correctWord: "people",
      },
      {
        id: "alexandria",
        name: "ALEXANDRIA UDOKA",
        statement: "I was one of the first ones out that day.",
        errorIdx: null,
      },
      {
        id: "montgomery",
        name: "MONTGOMERY EFFIONG",
        statement: "I wasn't even in the locker room that period.",
        errorIdx: null,
      },
    ],
    explanation: '"People" is the standard plural of "person"; "persons" is used only in narrow formal or legal contexts.',
    grammarType: "Irregular Plurals — person / people",
    usage: 'Use "people" as the everyday plural of "person" — save "persons" for formal or legal writing.',
    xp: 100,
  },
  {
    id: 50,
    level: 50,
    label: "CASE 50 · LEVEL 50",
    title: "The Hard Confession",
    briefing: "A student struggled to admit what really happened. Two classmates described the moment.",
    guiltySuspectId: "penelope",
    suspects: [
      {
        id: "fitzgerald",
        name: "FITZGERALD CHIDIEBERE",
        statement: "I told the coach myself right away, no issue.",
        errorIdx: null,
      },
      {
        id: "penelope",
        name: "PENELOPE ADAEZE",
        statement: "I couldn't bare to tell the coach what happened.",
        errorIdx: 2,
        correctWord: "bear",
      },
      {
        id: "seraphina",
        name: "SERAPHINA NGOZI",
        statement: "I wasn't there when the coach found out.",
        errorIdx: null,
      },
    ],
    explanation: '"Bear" (as a verb) means to endure; "bare" is an adjective meaning uncovered or empty.',
    grammarType: "Homophones — bare / bear",
    usage: 'Use "bear" for the verb meaning "to endure" ("couldn’t bear it"), and "bare" only as an adjective ("bare walls").',
    xp: 100,
  },
  {
    id: 51,
    level: 51,
    label: "CASE 51 · LEVEL 51",
    title: "The Nervous Wait",
    briefing: "A student waited anxiously outside the office for news. Two friends described trying to calm them down.",
    guiltySuspectId: "maxwell",
    suspects: [
      {
        id: "genevieve",
        name: "GENEVIEVE ADAORA",
        statement: "I waited with her the entire time outside.",
        errorIdx: null,
      },
      {
        id: "bartholomew",
        name: "BARTHOLOMEW IKENNA",
        statement: "I wasn't even at school that period, I was late.",
        errorIdx: null,
      },
      {
        id: "maxwell",
        name: "MAXWELL OLUWASEUN",
        statement: "I just wanted a peace of mind before the test.",
        errorIdx: 4,
        correctWord: "piece",
      },
    ],
    explanation: '"Piece" refers to a portion or part of something; "peace" refers to calm or the absence of conflict.',
    grammarType: "Homophones — peace / piece",
    usage: 'Use "piece" for a portion of something ("a piece of mind" is actually a mistake for "peace of mind" — use "peace" for calm).',
    xp: 100,
  },
  {
    id: 52,
    level: 52,
    label: "CASE 52 · LEVEL 52",
    title: "The Quick Glance",
    briefing: "A student claims to have seen the incident through a window. Two classmates questioned the sightline.",
    guiltySuspectId: "annabelle",
    suspects: [
      {
        id: "annabelle",
        name: "ANNABELLE OYELARAN",
        statement: "I threw a quick look threw the window before leaving.",
        errorIdx: 5,
        correctWord: "through",
      },
      {
        id: "barnaby",
        name: "BARNABY CHUKWUMA",
        statement: "I wasn't near any windows that whole period.",
        errorIdx: null,
      },
      {
        id: "rosaline",
        name: "ROSALINE NDIDI",
        statement: "I was outside, so I couldn't have seen anything.",
        errorIdx: null,
      },
    ],
    explanation: '"Threw" is the past tense of "throw"; "through" describes moving from one side of something to the other.',
    grammarType: "Homophones — threw / through",
    usage: 'Use "threw" for the past tense of "throw" ("threw a ball"), and "through" for movement across or inside something.',
    xp: 100,
  },
  {
    id: 53,
    level: 53,
    label: "CASE 53 · LEVEL 53",
    title: "The Fence Gap",
    briefing: "A gap in the back fence let someone slip off campus at lunch. Two students were seen near the fence line.",
    guiltySuspectId: "montgomery",
    suspects: [
      {
        id: "clementine",
        name: "CLEMENTINE OBIORA",
        statement: "I stayed on the blacktop the entire lunch period.",
        errorIdx: null,
      },
      {
        id: "montgomery",
        name: "MONTGOMERY ADAEZE",
        statement: "There was a whole in the fence by the gym.",
        errorIdx: 3,
        correctWord: "hole",
      },
      {
        id: "fitzwilliam",
        name: "FITZWILLIAM NNEKA",
        statement: "I was in the cafeteria the whole time, I have witnesses.",
        errorIdx: null,
      },
    ],
    explanation: '"Hole" refers to an opening or gap; "whole" means complete or entire.',
    grammarType: "Homophones — whole / hole",
    usage: 'Use "hole" for a gap or opening ("a hole in the fence"), and "whole" only to mean complete or entire.',
    xp: 100,
  },
];

// One tier per level, 1:1 with the reachable range (53 cases = levels
// 1-53) — every tier is something a player can really hit, none are
// dead/unreachable content. Levels 1-5 are unchanged from the original
// 3-case design; the rest extend the same one-rank-per-level pacing.
const RANK_TIERS = [
  "CADET",
  "OFFICER",
  "INSPECTOR",
  "DETECTIVE",
  "SENIOR DETECTIVE",
  "FIELD DETECTIVE",
  "CHIEF DETECTIVE",
  "LEAD INVESTIGATOR",
  "SENIOR INVESTIGATOR",
  "SPECIAL INVESTIGATOR",
  "SERGEANT",
  "SENIOR SERGEANT",
  "STAFF SERGEANT",
  "LIEUTENANT",
  "SENIOR LIEUTENANT",
  "CAPTAIN",
  "SENIOR CAPTAIN",
  "COMMANDER",
  "DEPUTY COMMANDER",
  "SENIOR COMMANDER",
  "BUREAU CHIEF",
  "DEPUTY CHIEF",
  "CHIEF INSPECTOR",
  "SENIOR CHIEF INSPECTOR",
  "PRECINCT CHIEF",
  "DIVISION CHIEF",
  "REGIONAL CHIEF",
  "DEPUTY COMMISSIONER",
  "ASSISTANT COMMISSIONER",
  "COMMISSIONER",
  "SENIOR COMMISSIONER",
  "CHIEF COMMISSIONER",
  "MASTER DETECTIVE",
  "ELITE DETECTIVE",
  "VETERAN DETECTIVE",
  "DECORATED DETECTIVE",
  "DISTINGUISHED DETECTIVE",
  "MASTER INVESTIGATOR",
  "ELITE INVESTIGATOR",
  "CHIEF STRATEGIST",
  "HEAD OF INVESTIGATIONS",
  "DIRECTOR OF OPERATIONS",
  "BUREAU DIRECTOR",
  "REGIONAL DIRECTOR",
  "NATIONAL INVESTIGATOR",
  "SENIOR NATIONAL INVESTIGATOR",
  "GRANDMASTER DETECTIVE",
  "LEGENDARY DETECTIVE",
  "MASTER SLEUTH",
  "GRAND INSPECTOR",
  "CHIEF OF DETECTIVES",
  "SUPREME INVESTIGATOR",
  "GRAMMAR DETECTIVE LEGEND",
] as const;

export function rankForLevel(level: number) {
  return RANK_TIERS[Math.min(level, RANK_TIERS.length) - 1];
}
